-- MySQL Script generated by MySQL Workbench
-- Sat Jan 16 16:14:29 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema Climb_9c
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Climb_9c
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Climb_9c` ;
USE `Climb_9c` ;

-- -----------------------------------------------------
-- Table `Climb_9c`.`CUSTOMER`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Climb_9c`.`CUSTOMER` (
  `idCUSTOMER` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `surname` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `telephone` VARCHAR(10) NOT NULL,
  `gender` TINYINT NULL DEFAULT NULL,
  `birthdate` DATE NOT NULL,
  PRIMARY KEY (`idCUSTOMER`),
  UNIQUE INDEX `idUTENTE_UNIQUE` (`idCUSTOMER` ASC),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Climb_9c`.`SELLER`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Climb_9c`.`SELLER` (
  `idSELLER` INT NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idSELLER`),
  UNIQUE INDEX `idSELLER_UNIQUE` (`idSELLER` ASC),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC),
  UNIQUE INDEX `password_UNIQUE` (`password` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Climb_9c`.`ADDRESS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Climb_9c`.`ADDRESS` (
  `idADDRESS` INT NOT NULL,
  `street` VARCHAR(45) NULL DEFAULT NULL,
  `number` VARCHAR(45) NULL DEFAULT NULL,
  `province` VARCHAR(45) NULL DEFAULT NULL,
  `city` VARCHAR(45) NULL DEFAULT NULL,
  `zip_code` VARCHAR(45) NULL DEFAULT NULL,
  `name` VARCHAR(45) NULL DEFAULT NULL,
  `surname` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idADDRESS`),
  UNIQUE INDEX `idADDRESS_UNIQUE` (`idADDRESS` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Climb_9c`.`CUSTOMER_ADDRESS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Climb_9c`.`CUSTOMER_ADDRESS` (
  `idCUSTOMER` INT NOT NULL,
  `idADDRESS` INT NOT NULL,
  `idCUSTOMER_ADDRESS` INT NOT NULL,
  INDEX `fk_CUSTOMER_ADDRESS_1_idx` (`idADDRESS` ASC),
  INDEX `fk_CUSTOMER_ADDRESS_2_idx` (`idCUSTOMER` ASC),
  PRIMARY KEY (`idCUSTOMER_ADDRESS`),
  UNIQUE INDEX `idCUSTOMER_ADDRESS_UNIQUE` (`idCUSTOMER_ADDRESS` ASC),
  CONSTRAINT `fk_CUSTOMER_ADDRESS_1`
    FOREIGN KEY (`idADDRESS`)
    REFERENCES `Climb_9c`.`ADDRESS` (`idADDRESS`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CUSTOMER_ADDRESS_2`
    FOREIGN KEY (`idCUSTOMER`)
    REFERENCES `Climb_9c`.`CUSTOMER` (`idCUSTOMER`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Climb_9c`.`COUPON`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Climb_9c`.`COUPON` (
  `code` VARCHAR(10) NOT NULL,
  `discount` VARCHAR(45) NOT NULL,
  `validity` TINYINT NOT NULL,
  PRIMARY KEY (`code`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Climb_9c`.`ORDER`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Climb_9c`.`ORDER` (
  `idORDER` INT NOT NULL,
  `date` DATE NOT NULL,
  `customer_address` INT NOT NULL,
  `shipping_date` DATE NULL,
  `COUPONcode` VARCHAR(10) NULL,
  PRIMARY KEY (`idORDER`),
  UNIQUE INDEX `idORDINE_UNIQUE` (`idORDER` ASC),
  INDEX `fk_ORDER_1_idx` (`COUPONcode` ASC),
  CONSTRAINT `fk_ORDER_1`
    FOREIGN KEY (`customer_address`)
    REFERENCES `Climb_9c`.`CUSTOMER_ADDRESS` (`idCUSTOMER_ADDRESS`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ORDER_2`
    FOREIGN KEY (`COUPONcode`)
    REFERENCES `Climb_9c`.`COUPON` (`code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Climb_9c`.`CATEGORY`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Climb_9c`.`CATEGORY` (
  `idCATEGORY` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idCATEGORY`),
  UNIQUE INDEX `idCATEGORY_UNIQUE` (`idCATEGORY` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Climb_9c`.`SUBCATEGORY`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Climb_9c`.`SUBCATEGORY` (
  `idSUBCATEGORY` INT NOT NULL,
  `idCATEGORY` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`idSUBCATEGORY`),
  UNIQUE INDEX `SUBCATEGORY_UNIQUE` (`idSUBCATEGORY` ASC),
  INDEX `fk_SUBCATEGORY_1_idx` (`idCATEGORY` ASC),
  CONSTRAINT `fk_SUBCATEGORY_1`
    FOREIGN KEY (`idCATEGORY`)
    REFERENCES `Climb_9c`.`CATEGORY` (`idCATEGORY`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Climb_9c`.`PRODUCT`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Climb_9c`.`PRODUCT` (
  `idPRODUCT` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `brand` VARCHAR(45) NOT NULL,
  `price` VARCHAR(45) NOT NULL,
  `idSUBCATEGORY` INT NOT NULL,
  `description` MEDIUMTEXT NOT NULL,
  `tecnical_specifications` JSON NOT NULL,
  `image_folder` VARCHAR(45) NOT NULL,
  `quantity` INT NOT NULL,
  PRIMARY KEY (`idPRODUCT`),
  UNIQUE INDEX `idPRODUCT_UNIQUE` (`idPRODUCT` ASC),
  INDEX `fk_PRODUCT_1_idx` (`idSUBCATEGORY` ASC),
  CONSTRAINT `fk_PRODUCT_1`
    FOREIGN KEY (`idSUBCATEGORY`)
    REFERENCES `Climb_9c`.`SUBCATEGORY` (`idSUBCATEGORY`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Climb_9c`.`TAG`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Climb_9c`.`TAG` (
  `idTAG` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`idTAG`),
  UNIQUE INDEX `idTAG_UNIQUE` (`idTAG` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Climb_9c`.`TAG_SUBCATEGORY`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Climb_9c`.`TAG_SUBCATEGORY` (
  `idTAG` INT NOT NULL,
  `idSUBCATEGORY` INT NOT NULL,
  PRIMARY KEY (`idTAG`, `idSUBCATEGORY`),
  INDEX `fk_TAG_SUBCATEGORY_2_idx` (`idSUBCATEGORY` ASC),
  CONSTRAINT `fk_TAG_SUBCATEGORY_1`
    FOREIGN KEY (`idTAG`)
    REFERENCES `Climb_9c`.`TAG` (`idTAG`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TAG_SUBCATEGORY_2`
    FOREIGN KEY (`idSUBCATEGORY`)
    REFERENCES `Climb_9c`.`SUBCATEGORY` (`idSUBCATEGORY`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Climb_9c`.`TAG_PRODUCT`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Climb_9c`.`TAG_PRODUCT` (
  `idTAG` INT NOT NULL,
  `idPRODUCT` INT NOT NULL,
  `value` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idTAG`, `idPRODUCT`),
  INDEX `fk_TAG_PRODUCT_2_idx` (`idPRODUCT` ASC),
  CONSTRAINT `fk_TAG_PRODUCT_1`
    FOREIGN KEY (`idTAG`)
    REFERENCES `Climb_9c`.`TAG` (`idTAG`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TAG_PRODUCT_2`
    FOREIGN KEY (`idPRODUCT`)
    REFERENCES `Climb_9c`.`PRODUCT` (`idPRODUCT`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Climb_9c`.`PRODUCT_ORDER`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Climb_9c`.`PRODUCT_ORDER` (
  `idPRODUCT` INT NOT NULL,
  `idORDER` INT NOT NULL,
  `quantity` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idPRODUCT`, `idORDER`),
  INDEX `fk_PRODUCT_ORDER_1_idx` (`idORDER` ASC),
  CONSTRAINT `fk_PRODUCT_ORDER_1`
    FOREIGN KEY (`idORDER`)
    REFERENCES `Climb_9c`.`ORDER` (`idORDER`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PRODUCT_ORDER_2`
    FOREIGN KEY (`idPRODUCT`)
    REFERENCES `Climb_9c`.`PRODUCT` (`idPRODUCT`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Climb_9c`.`CART`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Climb_9c`.`CART` (
  `idCUSTOMER` INT NOT NULL,
  `last_update` DATE NULL,
  PRIMARY KEY (`idCUSTOMER`),
  UNIQUE INDEX `idCUSTOMER_UNIQUE` (`idCUSTOMER` ASC),
  CONSTRAINT `fk_CART_1`
    FOREIGN KEY (`idCUSTOMER`)
    REFERENCES `Climb_9c`.`CUSTOMER` (`idCUSTOMER`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Climb_9c`.`CART_PRODUCT`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Climb_9c`.`CART_PRODUCT` (
  `idCART` INT NOT NULL,
  `idPRODUCT` INT NOT NULL,
  `quantity` INT NOT NULL,
  PRIMARY KEY (`idCART`, `idPRODUCT`),
  INDEX `fk_CART_PRODUCT_2_idx` (`idPRODUCT` ASC),
  CONSTRAINT `fk_CART_PRODUCT_1`
    FOREIGN KEY (`idCART`)
    REFERENCES `Climb_9c`.`CART` (`idCUSTOMER`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CART_PRODUCT_2`
    FOREIGN KEY (`idPRODUCT`)
    REFERENCES `Climb_9c`.`PRODUCT` (`idPRODUCT`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Climb_9c`.`REVIEW`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Climb_9c`.`REVIEW` (
  `idREVIEW` INT NOT NULL,
  `idCUSTOMER` INT NOT NULL,
  `idPRODUCT` INT NOT NULL,
  `title` VARCHAR(45) NULL,
  `comment` MEDIUMTEXT NULL,
  `vote` INT NULL,
  PRIMARY KEY (`idREVIEW`),
  UNIQUE INDEX `idREVIEW_UNIQUE` (`idREVIEW` ASC),
  INDEX `fk_REVIEW_1_idx` (`idCUSTOMER` ASC),
  INDEX `fk_REVIEW_2_idx` (`idPRODUCT` ASC),
  CONSTRAINT `fk_REVIEW_1`
    FOREIGN KEY (`idCUSTOMER`)
    REFERENCES `Climb_9c`.`CUSTOMER` (`idCUSTOMER`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_REVIEW_2`
    FOREIGN KEY (`idPRODUCT`)
    REFERENCES `Climb_9c`.`PRODUCT` (`idPRODUCT`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
