-- MySQL Script generated by MySQL Workbench
-- Mon Jan 18 14:04:44 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema climb_9c
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema climb_9c
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `climb_9c` ;
USE `climb_9c` ;

-- -----------------------------------------------------
-- Table `climb_9c`.`customer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `climb_9c`.`customer` (
  `idCUSTOMER` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `surname` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `telephone` VARCHAR(10) NOT NULL,
  `gender` TINYINT NULL DEFAULT NULL,
  `birthdate` DATE NOT NULL,
  PRIMARY KEY (`idCUSTOMER`),
  UNIQUE INDEX `idUTENTE_UNIQUE` (`idCUSTOMER` ASC),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `climb_9c`.`seller`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `climb_9c`.`seller` (
  `idSELLER` INT NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idSELLER`),
  UNIQUE INDEX `idSELLER_UNIQUE` (`idSELLER` ASC),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC),
  UNIQUE INDEX `password_UNIQUE` (`password` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `climb_9c`.`address`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `climb_9c`.`address` (
  `idADDRESS` INT NOT NULL,
  `street` VARCHAR(45) NULL DEFAULT NULL,
  `number` VARCHAR(45) NULL DEFAULT NULL,
  `province` VARCHAR(45) NULL DEFAULT NULL,
  `city` VARCHAR(45) NULL DEFAULT NULL,
  `zip_code` VARCHAR(45) NULL DEFAULT NULL,
  `name` VARCHAR(45) NULL DEFAULT NULL,
  `surname` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idADDRESS`),
  UNIQUE INDEX `idADDRESS_UNIQUE` (`idADDRESS` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `climb_9c`.`customer_address`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `climb_9c`.`customer_address` (
  `idCUSTOMER` INT NOT NULL,
  `idADDRESS` INT NOT NULL,
  `idCUSTOMER_ADDRESS` INT NOT NULL,
  INDEX `fk_CUSTOMER_ADDRESS_1_idx` (`idADDRESS` ASC),
  INDEX `fk_CUSTOMER_ADDRESS_2_idx` (`idCUSTOMER` ASC),
  PRIMARY KEY (`idCUSTOMER_ADDRESS`),
  UNIQUE INDEX `idCUSTOMER_ADDRESS_UNIQUE` (`idCUSTOMER_ADDRESS` ASC),
  CONSTRAINT `fk_CUSTOMER_ADDRESS_1`
    FOREIGN KEY (`idADDRESS`)
    REFERENCES `climb_9c`.`address` (`idADDRESS`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CUSTOMER_ADDRESS_2`
    FOREIGN KEY (`idCUSTOMER`)
    REFERENCES `climb_9c`.`customer` (`idCUSTOMER`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `climb_9c`.`coupon`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `climb_9c`.`coupon` (
  `code` VARCHAR(10) NOT NULL,
  `discount` VARCHAR(45) NOT NULL,
  `validity` TINYINT NOT NULL,
  PRIMARY KEY (`code`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `climb_9c`.`order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `climb_9c`.`order` (
  `idORDER` INT NOT NULL,
  `date` DATE NOT NULL,
  `customer_address` INT NOT NULL,
  `shipping_date` DATE NULL,
  `COUPONcode` VARCHAR(10) NULL,
  PRIMARY KEY (`idORDER`),
  UNIQUE INDEX `idORDINE_UNIQUE` (`idORDER` ASC),
  INDEX `fk_ORDER_1_idx` (`COUPONcode` ASC),
  CONSTRAINT `fk_ORDER_1`
    FOREIGN KEY (`customer_address`)
    REFERENCES `climb_9c`.`customer_address` (`idCUSTOMER_ADDRESS`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ORDER_2`
    FOREIGN KEY (`COUPONcode`)
    REFERENCES `climb_9c`.`coupon` (`code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `climb_9c`.`category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `climb_9c`.`category` (
  `idCATEGORY` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idCATEGORY`),
  UNIQUE INDEX `idCATEGORY_UNIQUE` (`idCATEGORY` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `climb_9c`.`subcategory`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `climb_9c`.`subcategory` (
  `idSUBCATEGORY` INT NOT NULL,
  `idCATEGORY` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`idSUBCATEGORY`),
  UNIQUE INDEX `SUBCATEGORY_UNIQUE` (`idSUBCATEGORY` ASC),
  INDEX `fk_SUBCATEGORY_1_idx` (`idCATEGORY` ASC),
  CONSTRAINT `fk_SUBCATEGORY_1`
    FOREIGN KEY (`idCATEGORY`)
    REFERENCES `climb_9c`.`category` (`idCATEGORY`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `climb_9c`.`product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `climb_9c`.`product` (
  `idPRODUCT` INT NOT NULL,
  `name` TINYTEXT NOT NULL,
  `brand` VARCHAR(45) NOT NULL,
  `price` DECIMAL(10,2) NOT NULL,
  `idSUBCATEGORY` INT NOT NULL,
  `description` MEDIUMTEXT NOT NULL,
  `tecnical_specifications` JSON NOT NULL,
  `quantity` INT NOT NULL,
  PRIMARY KEY (`idPRODUCT`),
  UNIQUE INDEX `idPRODUCT_UNIQUE` (`idPRODUCT` ASC),
  INDEX `fk_PRODUCT_1_idx` (`idSUBCATEGORY` ASC),
  CONSTRAINT `fk_PRODUCT_1`
    FOREIGN KEY (`idSUBCATEGORY`)
    REFERENCES `climb_9c`.`subcategory` (`idSUBCATEGORY`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `climb_9c`.`tag`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `climb_9c`.`tag` (
  `idTAG` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`idTAG`),
  UNIQUE INDEX `idTAG_UNIQUE` (`idTAG` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `climb_9c`.`tag_subcategory`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `climb_9c`.`tag_subcategory` (
  `idTAG` INT NOT NULL,
  `idSUBCATEGORY` INT NOT NULL,
  PRIMARY KEY (`idTAG`, `idSUBCATEGORY`),
  INDEX `fk_TAG_SUBCATEGORY_2_idx` (`idSUBCATEGORY` ASC),
  CONSTRAINT `fk_TAG_SUBCATEGORY_1`
    FOREIGN KEY (`idTAG`)
    REFERENCES `climb_9c`.`tag` (`idTAG`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TAG_SUBCATEGORY_2`
    FOREIGN KEY (`idSUBCATEGORY`)
    REFERENCES `climb_9c`.`subcategory` (`idSUBCATEGORY`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `climb_9c`.`tag_product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `climb_9c`.`tag_product` (
  `idTAG` INT NOT NULL,
  `idPRODUCT` INT NOT NULL,
  `value` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idTAG`, `idPRODUCT`),
  INDEX `fk_TAG_PRODUCT_2_idx` (`idPRODUCT` ASC),
  CONSTRAINT `fk_TAG_PRODUCT_1`
    FOREIGN KEY (`idTAG`)
    REFERENCES `climb_9c`.`tag` (`idTAG`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TAG_PRODUCT_2`
    FOREIGN KEY (`idPRODUCT`)
    REFERENCES `climb_9c`.`product` (`idPRODUCT`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `climb_9c`.`product_order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `climb_9c`.`product_order` (
  `idPRODUCT` INT NOT NULL,
  `idORDER` INT NOT NULL,
  `quantity` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idPRODUCT`, `idORDER`),
  INDEX `fk_PRODUCT_ORDER_1_idx` (`idORDER` ASC),
  CONSTRAINT `fk_PRODUCT_ORDER_1`
    FOREIGN KEY (`idORDER`)
    REFERENCES `climb_9c`.`order` (`idORDER`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PRODUCT_ORDER_2`
    FOREIGN KEY (`idPRODUCT`)
    REFERENCES `climb_9c`.`product` (`idPRODUCT`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `climb_9c`.`cart`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `climb_9c`.`cart` (
  `idCUSTOMER` INT NOT NULL,
  `last_update` DATE NULL,
  PRIMARY KEY (`idCUSTOMER`),
  UNIQUE INDEX `idCUSTOMER_UNIQUE` (`idCUSTOMER` ASC),
  CONSTRAINT `fk_CART_1`
    FOREIGN KEY (`idCUSTOMER`)
    REFERENCES `climb_9c`.`customer` (`idCUSTOMER`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `climb_9c`.`cart_product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `climb_9c`.`cart_product` (
  `idCART` INT NOT NULL,
  `idPRODUCT` INT NOT NULL,
  `quantity` INT NOT NULL,
  PRIMARY KEY (`idCART`, `idPRODUCT`),
  INDEX `fk_CART_PRODUCT_2_idx` (`idPRODUCT` ASC),
  CONSTRAINT `fk_CART_PRODUCT_1`
    FOREIGN KEY (`idCART`)
    REFERENCES `climb_9c`.`cart` (`idCUSTOMER`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CART_PRODUCT_2`
    FOREIGN KEY (`idPRODUCT`)
    REFERENCES `climb_9c`.`product` (`idPRODUCT`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `climb_9c`.`review`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `climb_9c`.`review` (
  `idREVIEW` INT NOT NULL,
  `idCUSTOMER` INT NOT NULL,
  `idPRODUCT` INT NOT NULL,
  `title` VARCHAR(45) NULL,
  `comment` MEDIUMTEXT NULL,
  `vote` INT NULL,
  PRIMARY KEY (`idREVIEW`),
  UNIQUE INDEX `idREVIEW_UNIQUE` (`idREVIEW` ASC),
  INDEX `fk_REVIEW_1_idx` (`idCUSTOMER` ASC),
  INDEX `fk_REVIEW_2_idx` (`idPRODUCT` ASC),
  CONSTRAINT `fk_REVIEW_1`
    FOREIGN KEY (`idCUSTOMER`)
    REFERENCES `climb_9c`.`customer` (`idCUSTOMER`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_REVIEW_2`
    FOREIGN KEY (`idPRODUCT`)
    REFERENCES `climb_9c`.`product` (`idPRODUCT`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
